version: '3'

services:
  site:
    build: .
    ports:
     - "8080:8080"
    environment:
     - NGINX_PORT=8080
    command: [nginx, '-g', 'daemon off;']
    logging:
      options:
        max-size: '10m'
    volumes:
     - ./config/nginx/templates:/etc/nginx/templates
